export enum CartActionTypes {
  ADD_TO_CART = 'ADD_TO_CART',
  MULTIPLY_PRODUCT = 'MULTIPLY_PRODUCT',
  REMOVE_FROM_CART = 'REMOVE_FROM_CART',
  LOAD_CART_PRODUCTS = 'LOAD_CART_PRODUCTS',
  CLEAR_CART = 'CLEAR_CART',
  MAKE_PAYMENT = 'MAKE_PAYMENT'
}
